<header>
    <div class="logo">
        <a href="bookRecord.php" >
            <h1><i class="fas fa-book text-primary"></i> The Book Spot</h1>
        </a>    
    </div>
    
    <div class="search">
        <h3>Administrator Dashboard</h3>
    </div>

    <div class="func">
        <a href='admin_profile.php'><i class='bi bi-person-circle'></i><span class='title'>Profile</span></a>
        <a href='inc/logout.inc.php'><i class='bi bi-lock'></i><span class='title'>Log Out</span></a>
    </div>
</header>
