<header>
    <div class="logo">
        <a href="index.php" >
            <h1> <i class="fas fa-book text-primary"></i> The Book Spot</h1>
        </a>    
    </div>
    
    <div class="search">
        <form action="">
            <input type="text" placeholder="Search..." name="search">
            <button type="submit"><i class="fa fa-search text-white"></i></button>
        </form>
    </div>

    <div class="func">
        <a href="">
            <span class="carticon">
                <i class="bi bi-cart carticon"></i>
                <span class="cart_count">2</span>
            </span> 
            <span class="cart">Cart</span></a>
        <a href=""><i class="bi bi-question-circle"></i><span class="help">Help</span></a>
    </div>
</header>
